// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAxNk3O1q_IIPNUbRkPvNvNCn3dIYzw0',
    appId: '1:318652470961:web:e0b45fcc444a929ad17490',
    messagingSenderId: '318652470961',
    projectId: 'todolist-ivanderwilson',
    authDomain: 'todolist-ivanderwilson.firebaseapp.com',
    storageBucket: 'todolist-ivanderwilson.firebasestorage.app',
    measurementId: 'G-BZP7Q7JSP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6dyb5roh6ejTuGxUYIGEvaE0R6zks7I',
    appId: '1:318652470961:android:66b1cf9718c58d53d17490',
    messagingSenderId: '318652470961',
    projectId: 'todolist-ivanderwilson',
    storageBucket: 'todolist-ivanderwilson.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5XSglKKfAiztPHvKh9pYuDxKz9UXYEhA',
    appId: '1:318652470961:ios:d3b97063d819cf18d17490',
    messagingSenderId: '318652470961',
    projectId: 'todolist-ivanderwilson',
    storageBucket: 'todolist-ivanderwilson.firebasestorage.app',
    iosBundleId: 'com.example.todolistivanderwilson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5XSglKKfAiztPHvKh9pYuDxKz9UXYEhA',
    appId: '1:318652470961:ios:d3b97063d819cf18d17490',
    messagingSenderId: '318652470961',
    projectId: 'todolist-ivanderwilson',
    storageBucket: 'todolist-ivanderwilson.firebasestorage.app',
    iosBundleId: 'com.example.todolistivanderwilson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsAxNk3O1q_IIPNUbRkPvNvNCn3dIYzw0',
    appId: '1:318652470961:web:65f498a9bf83f596d17490',
    messagingSenderId: '318652470961',
    projectId: 'todolist-ivanderwilson',
    authDomain: 'todolist-ivanderwilson.firebaseapp.com',
    storageBucket: 'todolist-ivanderwilson.firebasestorage.app',
    measurementId: 'G-E68BH2TND8',
  );
}
